### PR TITLE
Use HanSON to parse replace maps

### LINKED ISSUE #2: Add support for HanSON replace maps
I would like to use replaceinfiles to inject analytics codes into my HTML. One of JSON's limitations is the difficulty of using multi-line strings. HanSON is an extension to JSON that adds (among other things) ES6-style backtick-quoted multi-line strings.

**Example:**

```
{
  "input text": `some multi-line
output text`
}
```

All valid JSON is valid HanSON.

You can read more about it at https://github.com/timjansen/hanson.

Could replaceinfiles add support for HanSON replace maps?

I'd be willing to do a PR, just let me know!

### PR DESCRIPTION
**Pull request by RyanZim**
Fixes #2.

### CODE REVIEW

**Comment by ghost** [comment]
ping @saleandro

**Comment by RyanZim** [comment]
@ArnaudRinquin ping?

**Comment by ArnaudRinquin** [comment]
I don't have the rights on this project anymore and can't help you further.

Ping @saleandro @danlucraft @benhodgson87

**Comment by saleandro** [comment]
Thanks for submitting this PR, we'll review it as soon as we can.

**Comment by saleandro** [comment]
Ryan, thanks again for submitting your changes. We've discussed it internally and decided that supporting only JSON is enough for the use case of this project. We want to keep it simple and focused.

Hope it makes sense, and that this project is still useful for you in other ways.

**Pull request closed without merging**
